### ISSUE TITLE
Add vscode-dbt to extension manifest now that it's on marketplace

### ISSUE THREAD

**Issue by bastienboutonnet** [henriblancke/vscode-dbt-formatter#1]
nice formatter, I'll have to give it a whirl! FYI the `vscode-dbt` package is now published on the VSCode marketplace so you should be able to specify it as a dependency in your extension manifest. 
Here's a good documentation on how to do this: https://code.visualstudio.com/api/references/extension-manifest

**Comment by henriblancke** [comment]
Added in #2
